language: perl
jobs:
  include:
  - name: focal-arm64-graviton2
    dist: focal
    arch: arm64-graviton2
    os: linux
    group: edge
    virt: lxd
    perl: "5.30"
  - name: focal-arm64-graviton2b
    dist: focal
    arch: arm64-graviton2
    os: linux
    group: edge
    virt: lxd
    perl: "5.29"
script:
  - return 0
